style_defs = [
    '.dropbtn {',
    '  background-color: white;',
    '  color: blue;',
    '  text-decoration: underline;',
    '  padding: 0px;',
    '  font-size: 16px;',
    '  min-width: 100%;',
    '  border: none;',
    '}',

    '.dropdown {',
    '  position: relative;',
    '  display: inline-block;',
    '  min-width: 100%;',
    '}',

    '.dropdown-content {',
    '  display: none;',
    '  position: absolute;',
    '  background-color: #fafafa;',
    # '  min-width: 160px;',
    '  min-width: 100%;',
    # '  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);',
    '  z-index: 1;',
    '}',

    '.dropdown-content a {',
    '  color: black;',
    '  padding: 12px 16px;',
    '  text-decoration: none;',
    '  display: block;',
    '}',

    '.dropdown-content a:hover {background-color: #fafafa;}',
    '.dropdown:hover .dropdown-content {display: block;}',
    '.dropdown:hover .dropbtn {background-color: #fafafa;}',
]
