sites = [{'Name': 'Yaquina Head',
                                'lat': '44.67640', 'lon': '-124.07810', 'timezone_str': 'America/Los_Angeles',
                                'windDirLower': 270, 'windDirUpper': 360,
                                'windLower': 7, 'windUpper': 15,
                                'show_dewpoint': False, 'show_rh': False, 'show_skyCover': True,
                                'show_pop': True, 'show_qpf': True, 'show_snowAmt': False, 'show_snowLevel': False},  # TODO: Fix wind data
         {'Name': 'Cliffside',
                                'lat': '45.724844', 'lon': '-120.726470', 'timezone_str': 'America/Los_Angeles',
                                'windDirLower': 45, 'windDirUpper': 135,
                                'windLower': 7, 'windUpper': 15,
                                'show_dewpoint': False, 'show_rh': False, 'show_skyCover': True,
                                'show_pop': True, 'show_qpf': True, 'show_snowAmt': False, 'show_snowLevel': False},  # TODO: Fix wind data
         {'Name': 'Cape Kiwanda',
                                'lat': '44.690', 'lon': '-123.459', 'timezone_str': 'America/Los_Angeles',
                                'windDirLower': 270, 'windDirUpper': 360,
                                'windLower': 7, 'windUpper': 18,
                                'show_dewpoint': False, 'show_rh': False, 'show_skyCover': True,
                                'show_pop': True, 'show_qpf': True, 'show_snowAmt': False, 'show_snowLevel': False},  # TODO: Fix wind data
         {'Name': 'Area B',
                              'lat': '46.178162', 'lon': '-123.980713', 'timezone_str': 'America/Los_Angeles',
                              'windDirLower': 290, 'windDirUpper': 205,
                              'windLower': 12, 'windUpper': 14,
                              'show_dewpoint': False, 'show_rh': False, 'show_skyCover': True,
                              'show_pop': True, 'show_qpf': True, 'show_snowAmt': False, 'show_snowLevel': False},
         {'Name': 'Crestwood',
                                'lat': '45.333', 'lon': '-122.940', 'timezone_str': 'America/Los_Angeles',
                                'windDirLower': 225, 'windDirUpper': 270,
                                'windLower': 7, 'windUpper': 12,
                                'show_dewpoint': False, 'show_rh': False, 'show_skyCover': True,
                                'show_pop': True, 'show_qpf': True, 'show_snowAmt': False, 'show_snowLevel': False},  # TODO: Fix wind data
         {'Name': 'Mustang Peak',
                                'lat': '31.70407', 'lon': '-110.49246', 'timezone_str': 'America/Phoenix',
                                'windDirLower': 225, 'windDirUpper': 270,
                                'windLower': 4, 'windUpper': 14,
                                'show_dewpoint': False, 'show_rh': False, 'show_skyCover': False,
                                'show_pop': False, 'show_qpf': False, 'show_snowAmt': False, 'show_snowLevel': False}]
