sites = [{'Name': 'Yaquina Head',
                                'coords': 'lat=44.67640&lon=-124.07810',
                                'windDirLower': 270, 'windDirUpper': 360,
                                'windLower': 7, 'windUpper': 15,
                                'show_dewpoint': False, 'show_rh': False, 'show_skyCover': True,
                                'show_pop': True, 'show_qpf': True, 'show_snowAmt': False, 'show_snowLevel': False},  # TODO: Fix wind data
         {'Name': 'Cliffside',
                                'coords': 'lat=45.724844&lon=-120.726470',
                                'windDirLower': 45, 'windDirUpper': 135,
                                'windLower': 7, 'windUpper': 15,
                                'show_dewpoint': False, 'show_rh': False, 'show_skyCover': True,
                                'show_pop': True, 'show_qpf': True, 'show_snowAmt': False, 'show_snowLevel': False},  # TODO: Fix wind data
         {'Name': 'Cape Kiwanda',
                                'coords': 'lat=44.690&lon=-123.459',
                                'windDirLower': 270, 'windDirUpper': 360,
                                'windLower': 7, 'windUpper': 18,
                                'show_dewpoint': False, 'show_rh': False, 'show_skyCover': True,
                                'show_pop': True, 'show_qpf': True, 'show_snowAmt': False, 'show_snowLevel': False},  # TODO: Fix wind data
         {'Name': 'Crestwood',
                                'coords': 'lat=45.333&lon=-122.940',
                                'windDirLower': 225, 'windDirUpper': 270,
                                'windLower': 7, 'windUpper': 12,
                                'show_dewpoint': False, 'show_rh': False, 'show_skyCover': True,
                                'show_pop': True, 'show_qpf': True, 'show_snowAmt': False, 'show_snowLevel': False},  # TODO: Fix wind data
         {'Name': 'Mustang Peak',
                                'coords': 'lat=31.70407&lon=-110.49246',
                                'windDirLower': 225, 'windDirUpper': 270,
                                'windLower': 4, 'windUpper': 14,
                                'show_dewpoint': False, 'show_rh': False, 'show_skyCover': False,
                                'show_pop': False, 'show_qpf': False, 'show_snowAmt': False, 'show_snowLevel': False}]
